version: '2'

services:
  netcoredocker.web:
    image: netcoredocker.web:test
    ports:
      - "8011:80"

  netcoredocker.db:
    image: microsoft/mssql-server-linux:ctp-2.0
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P2ssw0rd
    volumes:
      - .\netcoredocker.db\:/var/opt/mssql/
    ports:
      - "1433:1433"