version: '2'

services:
  netcoredocker.web:
    image: netcoredocker.web:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - CONNECTIONSTRINGS_MSSQL=Server=tcp:netcoredocker.db,1433;Database=netcoredocker;User ID=sa;Password=P2ssw0rd;
    volumes:
      - ./netcoredocker.web:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  netcoredocker.db:
    image: microsoft/mssql-server-linux:ctp-2.0
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P2ssw0rd
    volumes:
      - .\netcoredocker.db\:/var/opt/mssql/
    ports:
      - "1433:1433"
